config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'welcome#index'

  get '/about_pop', controller: :about_pop, action: :index 
  get '/about_pop/board', controller: :about_pop, action: :board 
  get '/about_pop/faq', controller: :about_pop, action: :faq 
  get '/about_pop/manifesto', controller: :about_pop, action: :manifesto 
  get '/about_pop/staff', controller: :about_pop, action: :staff 

  get '/donate', controller: :donate, action: :index 
  get '/donate/levels', controller: :donate, action: :levels 

  get '/orchards', controller: :orchards, action: :index 
  get '/orchards/map', controller: :orchards, action: :map 
  get '/orchards/develop', controller: :orchards, action: :develop 
  get '/orchards/permaculture', controller: :orchards, action: :permaculture 
  get '/orchards/plants', controller: :orchards, action: :plants 
  get '/orchards/links', controller: :orchards, action: :links

  get '/volunteer/', controller: :volunteer, action: :index 
  get '/volunteer/signup', controller: :volunteer, action: :signup 
  get '/volunteer/schedule', controller: :volunteer, action: :schedule 
  get '/volunteer/committees', controller: :volunteer, action: :committees 

  get '/welcome/news', controller: :welcome, action: :news 

  resources :resources, only: [:index, :show]
  resources :rsvps, only: :create
end

app/views/shared/_buy_tickets.html.erb
<h3>PHILADELPHIA ORCHARD PROJECT MUSIC FESTIVAL</h3>

<p>
  Saturday, July 16 · 2:00pm - 8:00pm
  <br/>
  <%= link_to 'Liberty Lands Park', 'http://www.facebook.com/pages/Liberty-Lands-Park/147985388556362' %>, 3rd St. between Poplar St & Wildey St, Philadelphia, PA
</p>

<p>
Join us for the 3rd Annual "POP" Music Fest, the most fun urban farm fundraiser of the year!  Enjoy a beautiful day in the park and great music from 5 local bands: Faux Slang, Eric Carbonara + Jesse Sparhawk, Zillions + Blood Like Mine, The Old Fashioneds, and Pile of Girls.  Fish n'Chips DJs including Kyle M will keep you entertained between sets. Beer from the Philadelphia Brewing Company and food from Honest Tom's Taco Truck, Dapper Dog, and Buttercream Cupcake.  POP plant sale featuring figs, raspberries, strawberries, and more! 
</p>

<p>
Purchase $10 tickets in advance until July 11, 2011 (see below), $15 the day of the festival
<br/>
RAINDATE: Sunday, 7/17 @ 2pm
</p>

<div class="product"><input value="Music Festival Ticket"
class="product-title" type="hidden"><select
class="product-attr-custom"><option selected="selected"
googlecart-set-product-price="15.00" value="Regular">Regular -
$15.00</option><option googlecart-set-product-price="50.00"
value="Individual Sponsor">Individual Sponsor - $50.00</option><option
googlecart-set-product-price="200.00" value="Corporate
Sponsor">Corporate Sponsor - $200.00</option></select><input
value="15.00" class="product-price" type="hidden"><div title="Add to
cart" role="button" tabindex="0"
class="googlecart-add-button"></div></div>

<br/>
<br/>

app/views/shared/_full_planting_schedule.html.erb
<h3>EVENT SCHEDULE:
</h3>

<p>
  We invite you to participate by planting with POP, working alongside volunteers from our community partners to plant orchards all over the city. Volunteers of all ages and skill levels are welcome. These events involve digging, planting, and spreading compost and mulch, so expect to get dirty. We can't guarantee tools for all; if you bring your own, it is advisable to write your name on them. Snacks and beverages to share are also welcome.
</p>

<p>
  Planting events can generally be expected to last 3 or 4 hours. Please sign up for our volunteer email list for up-to-date info on events. We recommend that you check your email the morning of a planting to confirm whether if will be postponed to the raindate. Plantings happen in the spring and fall months.
</p>



<% for event in Event.upcoming(99) %>
  <fieldset class="event">
    <legend>
      <% if event.when_text.present? %>
        <%= event.when_text -%>
      <% else %>
        <%= event.when_starts.strftime "%A, %B %d" -%>... <%= event.when_starts.strftime "%I:%M %p" -%>
      <% end %>
    </legend>
    <p class="event_details">
      <b><%= "#{event.title}: " if event.title -%><%= event.place_name -%></b>
      <br/>(<%= event.address -%>)
      <br/><%= auto_link(event.description) -%>
    </p>

    <% if event.rsvp_allowed? %>
      <%= link_to 'RSVP...', "javascript:$('#rsvp_#{event.id}').slideToggle();" -%>

      <div id="rsvp_<%= event.id -%>" class="rsvp" style="display:block">

        <p>
        <% attending = event.rsvps.select &:attending? %>
        <% num_attending = attending.sum(&:how_many) %>
        <% unless attending.blank? %>
          <div class="attending">
            <i>Attending (<%= num_attending -%>):</i>
            <%= attending.map(&:name_with_bringing).join(', ').html_safe -%>
          </div>
        <% end %>

        <% not_attending = event.rsvps.select {|r| !r.attending?}  %>
        <% unless not_attending.blank? %>
          <div class="not_attending">
            <i>Not attending (<%= not_attending.size -%>):</i>
            <%= not_attending.map(&:name).join(', ') -%>
          </div>
        <% end %>

        <% if event.num_volunteers_needed %>
          <div class="num_volunteers_needed">
            <% if event.num_volunteers_needed < num_attending %>
              We have enough volunteers for this event!
            <% else %>
              <%= event.num_volunteers_needed - num_attending %> more volunteers needed!
            <% end %>
          </div>
        <% end %>
        </p>

        <% @rsvp = Rsvp.new event: event, attending: true,
           board_or_committee: false %>

        <%= form_for :rsvp, url: rsvps_path do |f| %>
        <%= f.hidden_field :event_id -%>
        Your name:
        <%= f.text_field :name, :size => 20-%>
        <br/><br/>
        Your email address:
        <%= f.text_field :email, :size => 20 -%>
        <br/><br/>
        Will you be joining us?
        &nbsp;
        <%= f.radio_button :attending, true, :onclick => "$('#extra_#{event.id}').slideDown();"  -%> Yes
        &nbsp;
        <%= f.radio_button :attending, false,
            onclick: "$('#extra_#{event.id}').slideUp();" -%> No
        <div id="extra_<%= event.id -%>">
          <br/>
          How many people will you bring (including yourself)?
          <%= f.text_field :how_many, :size => 2 -%>
          <br/><br/>
          Are you a member of the POP board or Orchard Committee?
          <br/>
          <%= f.radio_button :board_or_committee, true -%> Yes
          &nbsp;
          <%= f.radio_button :board_or_committee, false -%> No
        </div>

        <br/><br/>
        <%= submit_tag 'RSVP Now!' -%>
      <% end %>
    </div>
    <% end %>
  </fieldset>
<% end %>

<% if Event.upcoming.blank? %>
  <p>
    POP generally plants during the spring and fall. Check back for volunteer events or <%= link_to 'join our listserv', :controller => :volunteer, :action => :signup  %>.
  </p>
<% end %>

<%= clearboth -%>
<p> </p>
<p>
  Please contact <a href="mailto:phil@phillyorchards.org">phil@phillyorchards.org</a> for more information on a
  particular planting.
</p>

<h3><%= link_to 'Sign up now!', :controller => :volunteer, :action => :signup -%></h3>

app/views/shared/_pop_in_news.html.erb
<p>
	<table border="0" width="100%" cellpadding="10" cellspacing="0">
	<tr>
	<td style="color:#000000;font-family:Georgia,Times New Roman,Times,Serif;font-size:8pt" rowspan="1" align="left" colspan="1">
	<span style="color:#75a50e;font-family:Georgia,Times New Roman,Times,serif;font-size:18pt"><font color="#75a50e" size="5" face="Georgia,Times New Roman,Times,serif" style="color:#75a50e;font-family:Georgia,Times New Roman,Times,serif;font-size:18pt">POP in the News!</font></span><br><br>

  <% NewsStory.order("published_on desc").each { |story| %>

    <font size="2">&quot;<a href="<%= story.url -%>" target="_blank"><%= story.title -%></a>,&quot; <%= story.publisher -%>, <%= story.published_on.strftime '%m/%y' -%> <br><br>
     
  <% } %>
	</font></td>
	</tr>
	</table>	
</p>

app/views/shared/_upcoming.html.erb
<h3><%= link_to 'Upcoming Events', :controller => :volunteer, :action => :schedule -%></h3>

<% for event in Event.upcoming 99 %>

<p>
<%= "#{event.title}: " if event.title -%><%= event.place_name -%>       
<br/>
<%= event.when_starts.strftime "%A, %b %d" -%>
</p>
<% end %>

app/views/shared/_what_were_planting.html.erb
<h3>what we're planting:</h3>
<ul>
	<li>apples</li>
	<li>asian pears</li>
	<li>cherries</li>
	<li>figs</li>
	<li>pawpaws</li>
	<li>peaches</li>
	<li>pears</li>
	<li>persimmons</li>
	<li>plums</li>
	<li>serviceberries</li>
	<li>blackberries</li>
	<li>blueberries</li>
	<li>bush cherries</li>
	<li>currants</li>
	<li>elderberries</li>
	<li>gooseberries</li>
	<li>goumis</li>
	<li>hazelnuts</li>
	<li>raspberries</li>
	<li>grapes</li>
	<li>kiwis</li>
</ul>